language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
install: cpanm --with-develop --installdeps --notest .
script: perl Makefile.PL && make && cover -test
after_success:
  - cover -report coveralls

